### ISSUE TITLE
豆瓣api接口在小程序显示403

### ISSUE THREAD

**Issue by yuzd** [sesine/wechat-weapp-movie#12]
本地跑不起来

**Comment by sesine** [comment]
**发生此问题的原因**
微信开发者服务器请求豆瓣api次数过多，豆瓣禁止了从小程序发起的请求。

**此问题的解决方法**
现在的解决方法是用自己的服务器代理请求。请将原来的api请求地址从 `https://api.douban.com/v2/` 改为 `https://sesine.com/mina/api/` 即可，api请求的参数不变。
