### ISSUE TITLE
bug2 摇一摇没反应

### ISSUE THREAD

**Issue by wkcm** [sesine/wechat-weapp-movie#6]
系统类型： ios
手机品牌型号：苹果
console中的报错提示：真机
错误的截图：无
发生在什么情况下：摇一摇不好使，没反应

**Comment by shenzhuan** [comment]
后台在哪呢，还是没有开源？

**Comment by sesine** [comment]
> 后台在哪呢，还是没有开源？

后台api是豆瓣提供的，开放但不开源。

**Comment by sesine** [comment]
问题已修复，方法见此 [Commit](https://github.com/sesine/wechat-weapp-movie/commit/0d43b478f07655550547a8d921f50acc8f9cd848)
