### ISSUE TITLE
再次进入摇一摇页面不能摇了

### ISSUE THREAD

**Issue by luowenyue** [sesine/wechat-weapp-movie#9]
系统类型： ios
手机品牌型号：苹果
console中的报错提示：真机
错误的截图：无
发生在什么情况下：再次进入摇一摇页面不能摇了
看你的日志也提到了 过去这么久 请问可能是什么原因 ？

**Comment by sesine** [comment]
问题已修复，方法见此 [Commit](https://github.com/sesine/wechat-weapp-movie/commit/0d43b478f07655550547a8d921f50acc8f9cd848)
